### ISSUE TITLE
node16 deprecated, upgrade to node20

### ISSUE THREAD

**Issue by jazanne** [zentered/vercel-preview-url#156]
**Describe the bug**
Warning message when running action

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: zentered/vercel-preview-url@v1.1.9. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**To Reproduce**
Run action in any workflow

**Expected behavior**
Use node20

**Comment by PatrickHeneise** [comment]
Thanks @jazanne!

**Comment by jazanne** [comment]
@PatrickHeneise wow thanks for the quick turn around on this!
