### ISSUE TITLE
Return the branch_alias

### ISSUE THREAD

**Issue by emerson-paiva** [zentered/vercel-preview-url#158]
First of all, thanks for this action 

**Is your feature request related to a problem? Please describe.**
Is not a problem itself, but would improve my workflow.

In my workflow we grab the preview_url and define this as an iframe URL to a wrapper that we have, right know I'm using the preview_url that changes in every new deploy, so I need to run the workflow in every deploy from the Pull Request, but if the lib returns the `branchAlias`, I would use the branch_alias (that's updated in every commit) as URL, so my workflow would only run once. 

**Describe the solution you'd like**
- Add `branch_alias` to [output](https://github.com/zentered/vercel-preview-url/blob/03056a9d50b7a471391549038d2c40a8a4eceb0e/src/index.js#L33)

**Comment by PatrickHeneise** [comment]
Hi @emerson-paiva! Where does the `branch_alias` come from? It's been a while I've looked into the Vercel API. If you can create a Pull Request for the change, I'll happily merge that.

**Comment by emerson-paiva** [comment]
Thanks @PatrickHeneise!
