### ISSUE TITLE
Action ignores project_id in the inputs

### ISSUE THREAD

**Issue by mxseev** [zentered/vercel-preview-url#93]
**Describe the bug**
Action ignores `project_id` in the inputs and returns the deployment URL of the wrong project in monorepo

**To Reproduce**
1. Create monorepo with multiple Vercel projects
2. Type correct project_id to action inputs
3. Try to run workflow
4. See deployment URL for wrong project

**Expected behavior**
Action outputs deployment URL for project with `project_id`, not other project in repository

**Actual behavior**
Action outputs the URL of the wrong deployment (other project in monorepo) 

**Additional context**
In the code, you can see that the project_id input is completely ignored and just [commented](https://github.com/zentered/vercel-preview-url/blob/main/vercel.mjs#L11) out. Why?

**Comment by PatrickHeneise** [comment]
Thanks for flagging this. I think at the time there were issues with the `projectId` being ignored by the API or because it's not required we decided to keep things simple. Feel free to create a PR with a fix for monorepos, I'll merge that.
